version: '3'

services:

  prometheus:
    user: root
    image: prom/prometheus:latest
    command: ["--config.file=/prometheus-config/prometheus.yaml"]
    volumes:
      - ./config:/prometheus-config
      - ./data/prometheus:/prometheus
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana
    volumes:
      - ./data/grafana:/var/lib/grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus